# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCliTools < Formula
  desc ""
  homepage "https://github.com/Caspian-X/homebrew-tools"
  version "1.3.2"

  on_macos do
    on_intel do
      url "https://github.com/Caspian-X/homebrew-tools/releases/download/v1.3.2/homebrew-tools_Darwin_x86_64.tar.gz"
      sha256 "371ec3e130908c5333bfd1742f5c76da7640e9608f30ee9c9c0c6dcaae934254"

      def install
        bin.install "convert-heic-to-jpg"
        bin.install "date-photos"
        bin.install "remove-duplicate-photos"
        bin.install "remove-files"
      end
    end
    on_arm do
      url "https://github.com/Caspian-X/homebrew-tools/releases/download/v1.3.2/homebrew-tools_Darwin_arm64.tar.gz"
      sha256 "a15dc158a177e6a53553720b2269c1b25beea3c71706a7eb5e0d92b4843ef5d1"

      def install
        bin.install "convert-heic-to-jpg"
        bin.install "date-photos"
        bin.install "remove-duplicate-photos"
        bin.install "remove-files"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Caspian-X/homebrew-tools/releases/download/v1.3.2/homebrew-tools_Linux_x86_64.tar.gz"
        sha256 "94bcc997a39343baf9dd206af3bf2f6145a04193d3211b6c0a98ca39be456619"

        def install
          bin.install "convert-heic-to-jpg"
          bin.install "date-photos"
          bin.install "remove-duplicate-photos"
          bin.install "remove-files"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Caspian-X/homebrew-tools/releases/download/v1.3.2/homebrew-tools_Linux_arm64.tar.gz"
        sha256 "f69740d54cb5b6b9e85212f3f66f5fe5056cbdbc78c9f4b486279130133dcafd"

        def install
          bin.install "convert-heic-to-jpg"
          bin.install "date-photos"
          bin.install "remove-duplicate-photos"
          bin.install "remove-files"
        end
      end
    end
  end
end
