# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-cli-tools" do
  name "go-cli-tools"
  desc ""
  homepage "https://github.com/Caspian-X/homebrew-tools"
  version "1.7.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "date-photos"
  binary "remove-duplicate-photos"
  binary "remove-files"
  binary "convert-heic-to-jpg"
  binary "convert-m4a-to-mp3"
  binary "normalize-audio"
  binary "dir-compare"
  binary "check-thumbnails"

  on_macos do
    on_intel do
      url "https://github.com/Caspian-X/homebrew-tools/releases/download/v#{version}/homebrew-tools_Darwin_x86_64.tar.gz"
      sha256 "be4eb9990c6471eb237d1ed4a6c24aca576b602ca60e8008cf0b7e7021373476"
    end
    on_arm do
      url "https://github.com/Caspian-X/homebrew-tools/releases/download/v#{version}/homebrew-tools_Darwin_arm64.tar.gz"
      sha256 "8ef554cd5d29a124c88186267a61611254d5a639e0aa325a279144166d7e5023"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Caspian-X/homebrew-tools/releases/download/v#{version}/homebrew-tools_Linux_x86_64.tar.gz"
      sha256 "eb15920b8cbdd4e64952664c53c2d1e43b9fd4dab898e8127281e85484ee6a85"
    end
    on_arm do
      url "https://github.com/Caspian-X/homebrew-tools/releases/download/v#{version}/homebrew-tools_Linux_arm64.tar.gz"
      sha256 "1780d68385a6e472b00c77e5a7b3bd529c1bb863aadbdfbafcbab1cd8b272f4b"
    end
  end

  # No zap stanza required
end
