# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-cli-tools" do
  name "go-cli-tools"
  desc ""
  homepage "https://github.com/Caspian-X/homebrew-tools"
  version "1.7.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-cli-tools"

  on_macos do
    on_intel do
      url "https://github.com/Caspian-X/homebrew-tools/releases/download/v#{version}/homebrew-tools_Darwin_x86_64.tar.gz"
      sha256 "32e6e92c159b92df423266c28437adf83ebc2b346a04ea7862ad587c9bcb91d5"
    end
    on_arm do
      url "https://github.com/Caspian-X/homebrew-tools/releases/download/v#{version}/homebrew-tools_Darwin_arm64.tar.gz"
      sha256 "68e6659babafaa42281028701ba7121f004392ca08ec6e16df5108c1b1873b98"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Caspian-X/homebrew-tools/releases/download/v#{version}/homebrew-tools_Linux_x86_64.tar.gz"
      sha256 "fe0a215a12633c580d464d2b2d15027f1078f5b23afe4fb83f41c206026d2f87"
    end
    on_arm do
      url "https://github.com/Caspian-X/homebrew-tools/releases/download/v#{version}/homebrew-tools_Linux_arm64.tar.gz"
      sha256 "f5d143369217a5a66e0c313809d51b264729d6c7cb5ce04a8111463bfb382d36"
    end
  end

  # No zap stanza required
end
