# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-cli-tools" do
  name "go-cli-tools"
  desc ""
  homepage "https://github.com/Caspian-X/homebrew-tools"
  version "1.7.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-cli-tools"

  on_macos do
    on_intel do
      url "https://github.com/Caspian-X/go-cli-tools/releases/download/v#{version}/go-cli-tools_Darwin_x86_64.tar.gz"
      sha256 "de3eb1286eb634ab6c8d2d680ef659ba257960201ece8b89fcbd454be6172e58"
    end
    on_arm do
      url "https://github.com/Caspian-X/go-cli-tools/releases/download/v#{version}/go-cli-tools_Darwin_arm64.tar.gz"
      sha256 "f7ae14ba86eabc0e30677e58ef9423c89e9c88ccf6c64565e818b8d055b4dac6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Caspian-X/go-cli-tools/releases/download/v#{version}/go-cli-tools_Linux_x86_64.tar.gz"
      sha256 "f9f941bb839436fc08b63cf3e4d0c4152f1b65c3db5145233ccb57cd873fb2a3"
    end
    on_arm do
      url "https://github.com/Caspian-X/go-cli-tools/releases/download/v#{version}/go-cli-tools_Linux_arm64.tar.gz"
      sha256 "04ba832db53eae6b43dfc938103e06d1c9711f4b4ef1d422f1815b6fd584b2f2"
    end
  end

  # No zap stanza required
end
